//AUTH
export const GET_AUTH_START = 'GET_AUTH_START';
export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
export const GET_AUTH_FAIL = 'GET_AUTH_FAIL';

export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const SIGN_OUT_START = 'SIGN_IN_START';
export const SIGN_OUT_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_IN_FAIL';

//Toggle states
export const SHOW_POPUP = 'SHOW_POPUP';
export const SET_IS_EDITING = 'SET_IS_EDITING';
export const UPDATE_VIEWPORT = 'UPDATE_VIEWPORT';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const SET_ADD_ENTRY_LOCATION = 'SET_ADD_ENTRY_LOCATION';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const TOGGLE_USER_DRAWER = 'TOGGLE_USER_DRAWER';

/**
 * ----------------- ASYNCHRONOUS ACTIONS -----------------
 */
//FETCH ACTION
export const FETCH_ENTRIES_START = 'FETCH_ENTRIES_START';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAIL = 'FETCH_ENTRIES_FAIL';

//POST ACTION
export const IS_ADDING_MARK = 'IS_ADDING_MARK';
export const POST_ENTRY_START = 'POST_ENTRY_START';
export const POST_ENTRY_SUCCESS = 'POST_ENTRY_SUCCESS';
export const POST_ENTRY_FAIL = 'POST_ENTRY_FAIL';

//EDIT ACTION
export const IS_EDITING_ENTRY = 'IS_EDITING_ENTRY';
export const POST_EDIT_START = 'POST_EDIT_START';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAIL = 'POST_EDIT_FAIL';

//DELETE ACTION
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';